version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:4.28
    depends_on:
      - db
    volumes:
      - ./liquibase:/liquibase/changelog
    command: >
      update
      --url=jdbc:postgresql://db:5432/blogdb
      --changeLogFile=changelog/changelog.xml
      --username=postgres
      --password=password
    environment:
      - LIQUIBASE_LOG_LEVEL=info

  api:
    build: .
    depends_on:
      - db
      - liquibase
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: blogdb
      PGPORT: 5432
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata:
