version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: blogdb_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:4.28
    depends_on:
      - db
    volumes:
      - ./liquibase:/liquibase/changelog
    command: >
      sh -c "liquibase update --url=jdbc:postgresql://db:5432/blogdb_test --changeLogFile=changelog/changelog.xml --username=postgres --password=password && tail -f /dev/null"
    environment:
      - LIQUIBASE_LOG_LEVEL=info
    healthcheck:
      test: ["CMD-SHELL", "sleep 10s"]
      interval: 1s
      timeout: 11s
      retries: 5

  test:
    build: 
      context: .
      args:
        NODE_ENV: development
    depends_on:
      liquibase:
        condition: service_healthy
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: blogdb_test
      PGPORT: 5432
      NODE_ENV: development

    command: ["npm", "test"]


volumes:
  pgdata_test:
